model_name: resfcn
test:
  resume_path: /data_static/dongchengbo/best_models/release_resfcn_oncasia33.pt
  test_file: /data_activate/dongchengbo/VisualSearch/Columbia_full/annotations/Columbia_full.txt
  save_dir: ../save_dir
  resize: 512
